# ─── Site Settings ────────────────────────────────────────────────
title: "UAP Manila Corinthian Chapter"
description: "Premier community of architectural professionals in Manila. Join events, workshops, and networking opportunities."
url: "https://uapmnlcorinthian.com"  # ✅ Update to live domain
baseurl: ""  # Leave blank if deploying to root (GitHub Pages w/ custom domain)

lang: "en"  # ✅ Helps with SEO & accessibility
timezone: "Asia/Manila"
future: true

# ─── SEO Defaults ─────────────────────────────────────────────────
author: "UAP Manila Corinthian"
logo: "https://asset.manilacorinthianchapter.workers.dev/MCC%20LOGO.png"
social:
  name: "UAP Manila Corinthian Chapter"
  links:
    - https://www.facebook.com/manilacorinthianchapter
    - https://www.instagram.com/uapmanilacorinthian/
    - https://x.com/uapmnlcorinth
    - mailto:info@uapmnlcorinthian.com

# ─── Build Settings ───────────────────────────────────────────────
markdown: kramdown
permalink: pretty
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

# ─── Plugins ──────────────────────────────────────────────────────
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-include-cache

# ─── Collections ──────────────────────────────────────────────────
collections:
  events:
    output: true
    permalink: /events-and-activities/:path/

# ─── Defaults ─────────────────────────────────────────────────────
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      lang: "en"
      author: "UAP Manila Corinthian"
      image: "https://asset.manilacorinthianchapter.workers.dev/preview.jpg"
      description: "Official page of UAP Manila Corinthian Chapter"

  - scope:
      path: ""
      type: "events"
    values:
      layout: event
      lang: "en"
      author: "UAP Manila Corinthian"

# ─── Include & Exclude ────────────────────────────────────────────
include:
  - admin

exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - account1.html
  - activities1.html
  - bod1.html
  - index1.html
  - login1.html
  - LOCAL HOST.bat
  - MCC WEBSITE rebuild .bat
  - space remover.bat
