# ─── Site Settings ────────────────────────────────────────────────
title: "UAP Manila Corinthian Chapter"
description: "Premier community of architectural professionals in Manila. Join events, workshops, and networking opportunities."
url: "https://manilacorinthianchapter.github.io"    # no trailing slash
baseurl: "/mcc"                                      # your repo subpath

# ─── Build Options ───────────────────────────────────────────────
markdown: kramdown
permalink: pretty                                   # /about/ instead of /about.html

# ─── Layout Defaults ─────────────────────────────────────────────
defaults:
  - scope:
      path: ""         # all files
      type: "pages"    # apply to pages
    values:
      layout: "default"  # uses _layouts/default.html

# ─── Plugins (GitHub Pages–supported) ────────────────────────────
plugins:
  - jekyll-feed           # generates an RSS feed at /feed.xml
  - jekyll-seo-tag        # injects SEO meta tags automatically

# ─── Exclude from Build ──────────────────────────────────────────
exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor

# ─── Optional Customizations ──────────────────────────────────────
# You can override directories if needed:
# includes_dir: _includes
# layouts_dir:  _layouts
# data_dir:     _data

  # Project: UAP Manila Corinthian Chapter Website
  # Author: ArZ Miranda
  # Date Created: 2025-07-19
  # Last Modified: 2025-07-19
  # Version: 1.0.0

  # Description:
    # This script powers the interactive features of the UAP Manila Corinthian Chapter (MCC) website.
    # It enables members to securely log in and view their personalized account information,
    # including membership status, payment history, and contact details.
    # The script also enhances the user experience by providing convenient tools such as password visibility toggling
    # and easy options to save or print membership data.
    # Data shown is dynamically updated from the MCC membership database to ensure accuracy and relevance.

  # Usage:
    # - This script expects specific DOM elements present on the page:
      # - Login page: #loginForm, username and password inputs, toggle password button.
      # - Account page: Elements with IDs such as #cardName, #statusBadge, #totalDue,
        # payment tables (#paymentsTable), and toggle-sensitive buttons.
    # - It relies on Bootstrap 5 for styling and interactivity,
      # FontAwesome 6 for icons,
      # and Supabase JS SDK v2 for backend database interactions.
    # - User session data is stored in sessionStorage under 'userData' key.
    # - Account info is auto-populated on page load if valid session data exists.

  # Dependencies:
    # - Supabase JavaScript SDK v2 (https://supabase.com/docs/reference/javascript/installing)
    # - Bootstrap 5 CSS & JS (https://getbootstrap.com/)
    # - FontAwesome 6 Icons (https://fontawesome.com/)

  # Change Log:
    # 2025-07-19 - v1.0.0 - Initial implementation with login, session handling, account rendering, and usability features.

  # Notes:
    # - Ensure that the <body> tag on the account page includes the 'account-info' class to trigger account initialization.
    # - Sensitive member data such as PRC License, Email, and Contact Number are masked by default and toggleable for user convenience.
    # - Payment data columns for different years are dynamically retrieved from Supabase for future-proofing.
    # - Right-click and keyboard shortcut blocking have been disabled to improve user experience.

  # Contact:
    # UAP Manila Corinthian Chapter
    # Email: uapmccmembership@gmail.com
    # Website: https://manilacorinthianchapter.github.io/mcc/

  # License:
    # Proprietary - For internal use by UAP MCC only
 
  # __  __  _____ _____   ___   ___ ___  _____            _____   ______
 # |  \/  |/ ____/ ____| |__ \ / _ \__ \| ____|     /\   |  __ \ |___  /
 # | \  / | |   | |         ) | | | | ) | |__      /  \  | |__) |   / / 
 # | |\/| | |   | |        / /| | | |/ /|___ \    / /\ \ |  _  /   / /  
 # | |  | | |___| |____   / /_| |_| / /_ ___) |  / ____ \| | \ \  / /__ 
 # |_|  |_|\_____\_____| |____|\___/____|____/  /_/    \_\_|  \_\/_____|