# ─── Site Settings ────────────────────────────────────────────────
title: "UAP Manila Corinthian Chapter"
description: "Premier community of architectural professionals in Manila. Join events, workshops, and networking opportunities."
url: "http://uapmnlcorinthian.github.io"    # no trailing slash
baseurl: ""                                 # your repo subpath

# ─── Build Options ─────────────────────────────────────────────
markdown: kramdown
permalink: pretty                           # /about/ instead of /about.html
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed                         # Minify CSS output
timezone: Asia/Manila

# ─── Collections ─────────────────────────────────────────────────
data_pages:
  events:
    template: event               # uses _layouts/event.html
    dir: events-and-activities    # output folder
    name: ":slug/index"           # use each item’s `slug` field
    extension: "html"             # .html appended automatically

# ─── Default Layouts for Types ──────────────────────────────────
defaults:
  # regular pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      
 # event collection items
  - scope:
      path: ""
      type: "events"
    values:
      layout: event
      
collections:
  events:
    output: true
    permalink: /events-and-activities/:path/
    
# ─── Plugins ─────────────────────────────────────────────────────
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-include-cache
  - jekyll-datapage-generator

# ─── Include & Exclude ───────────────────────────────────────────
include:
  - admin

exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - account1.html
  - activities1.html
  - bod1.html
  - index1.html
  - login1.html
  - LOCAL HOST.bat
  - MCC WEBSITE rebuild .bat
  - space remover.bat
