# ─── Site Settings ────────────────────────────────────────────────
title: "UAP Manila Corinthian Chapter"
description: "Premier community of architectural professionals in Manila. Join events, workshops, and networking opportunities."
url: "http://uapmnlcorinthian.github.io"
baseurl: ""

# ─── Build Options ─────────────────────────────────────────────
markdown: kramdown
permalink: pretty
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: Asia/Manila

# ─── Default Layouts for Types ──────────────────────────────────
defaults:
  # regular pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      
 # event collection items
  - scope:
      path: ""
      type: "events"
    values:
      layout: event
      
collections:
  events:
    output: true
    permalink: /events-and-activities/:path/
    
# ─── Plugins ─────────────────────────────────────────────────────
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-include-cache

# ─── Include & Exclude ───────────────────────────────────────────
include:
  - admin

exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - account1.html
  - activities1.html
  - bod1.html
  - index1.html
  - login1.html
  - LOCAL HOST.bat
  - MCC WEBSITE rebuild .bat
  - space remover.bat
