[build]
  publish = "_site"
  command = "bundle exec jekyll build"
  # (do NOT set base here when this file is in mcc.2025)

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"
