<!-- File: /admin/config.yml -->
backend:
  name: github
  repo: uapmnlcorinthian/uapmnlcorinthian.github.io   # e.g. “uapmnlcorinthian/website”
  branch: main
  auth_scope: "repo"              # if you need write access
  auth_endpoint: ""               # leave blank for Netlify CMS default

media_folder: "assets/img"
public_folder: "/assets/img"
collections:
  - name: "sponsors"
    label: "Sponsors"
    folder: "_data"
    create: true
    extension: "yml"
    slug: "{{slug}}"
    fields:
      - {label: "Name",         name: "name",    widget: "string"}
      - {label: "Website URL",  name: "website", widget: "string"}
      - {label: "Logo",         name: "logo",    widget: "image"}
      - {label: "Alt Text",     name: "alt",     widget: "string"}
      - {label: "Tier",         name: "tier",    widget: "select", options: ["Platinum","Gold","Silver","Bronze","Event"]}
      - {label: "Active?",      name: "active",  widget: "boolean", default: true}
      - {label: "Order",        name: "order",   widget: "number", default: 1}
      - {label: "Tagline",      name: "tagline", widget: "string", required: false}
      - {label: "Start Date",   name: "start_date", widget: "datetime", required: false}
      - {label: "End Date",     name: "end_date",   widget: "datetime", required: false}
      - {label: "Media Type",   name: "media_type", widget: "select", options: ["image","video"], default: "image"}
      - {label: "Media URL",    name: "media_url",  widget: "string", required: false}

