# File: /admin/config.yml

backend:
  name: github
  repo: uapmnlcorinthian/uapmnlcorinthian.github.io 
  branch: main
  base_url: "/"                 # site root
  auth_endpoint: "/.netlify/functions/auth"

local_backend: true

media_folder: "images"
public_folder: "/images"

publish_mode: editorial_workflow
editor:
  preview: true
  preview_url: "/events/{{slug}}/"

collections:
  - name: "sponsors"
    label: "Sponsors"
    folder: "_data/sponsors"
    create: true
    slug: "{{fields.name | slugify}}"
    extension: "yml"
    summary: "{{fields.name}} ({{fields.tier}})"
    fields:
      - {label: "Name",         name: "name",        widget: "string"}
      - {label: "Website URL",  name: "website",     widget: "string"}
      - {label: "Logo",         name: "logo",        widget: "image"}
      - {label: "Alt Text",     name: "alt",         widget: "string"}
      - {label: "Tier",         name: "tier",        widget: "select", options: ["Platinum","Gold","Silver","Bronze","Supporting","Event"]}
      - {label: "Active?",      name: "active",      widget: "boolean"}
      - {label: "Order",        name: "order",       widget: "number"}
      - {label: "Tagline",      name: "tagline",     widget: "string", required: false}
      - {label: "Start Date",   name: "start_date",  widget: "datetime", required: false}
      - {label: "End Date",     name: "end_date",    widget: "datetime", required: false}
      - {label: "Media Type",   name: "media_type",  widget: "select", options: ["image","video"], default: "image"}
      - {label: "Media URL",    name: "media_url",   widget: "string", required: false}
      - {label: "Contact Email",name: "contact_email",widget: "string"}

  - name: "events"
    label: "Events"
    folder: "_data/events"
    create: true
    slug: "{{fields.title | slugify}}"
    extension: "yml"
    summary: "{{fields.title}} ({{fields.event_date}})"
    fields:
      - {label: "Title",           name: "title",            widget: "string"}
      - {label: "Draft?",          name: "draft",            widget: "boolean", default: true}
      - {label: "Event Date",      name: "event_date",       widget: "date",   format: "yyyy-MM-dd"}
      - {label: "Category",        name: "category",         widget: "string"}
      - {label: "Location",        name: "location",         widget: "string"}
      - {label: "Registration URL",name: "registration_url", widget: "string", required: false}
      - {label: "Map Embed",       name: "map_embed",        widget: "text",   required: false, hint: "Full <iframe> embed code"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        allow_add: true
      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        allow_add: true
        fields:
          - {label: "URL",     name: "url",     widget: "image"}
          - {label: "Alt",     name: "alt",     widget: "string"}
          - {label: "Caption", name: "caption", widget: "string"}
      - {label: "Description",    name: "description", widget: "text"}
      - {label: "Body",           name: "body",        widget: "markdown"}
