name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-build-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: |
            ~/.bundle
            vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site --verbose

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Download Pages artifact
        uses: actions/download-pages-artifact@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
